### ISSUE TITLE
Don't tell people to use VDatum!

### ISSUE THREAD

**Issue by hobu** [dmahr1/ihatecoordinatesystems#1]
PROJ 7.0+ can handle the vertical transformations that VDatum can in a much more convenient form. All of the shift files are even available from cdn.proj.org to be lazily used by PROJ.

**Comment by dmahr1** [comment]
@hobu Thanks for the tip. I'm still on PROJ 6.x and didn't know 7.x could do vertical transformations like this. Very neat.

**Comment by dmahr1** [comment]
I just merged a change that mentions `cs2cs` first and VDatum as a backup:
![image](https://user-images.githubusercontent.com/8354515/89947404-674eaf80-dbf2-11ea-9dd8-b7c31c7c52d2.png)

Thanks again. And I'm a big PDAL fan, thanks for all your hard work on that project.
