### ISSUE TITLE
Reverse Lookup No Longer Functioning

### ISSUE THREAD

**Issue by BrianZ111** [dmahr1/ihatecoordinatesystems#7]
Recently the reverse lookup function has stopped working for me.  It just hangs on "Searching for projections... (this can take up to 30 seconds)".  Whatever the issue is, I was able to get around it.  I downloaded the python script and rewrote the handler function to just hard code the lat, long, x, and y coordinates and print the response_dicts variable and it worked.  So it's some issue interfacing with the webpage.

Thanks for putting this together.  I've been using the reverse lookup feature somewhat frequently since I discovered this page about 4 months ago.  I sometimes get sent CAD files from people who did not create them and I have to load them in GIS software.  It's often times a lot easier to use this than try to track down the person who actually knows what coordinate system was used in the file.

**Comment by dmahr1** [comment]
@BrianZ111 Thanks for the bug report. Can you try it again? This script is deployed as a cloud function and I had to refresh something.

**Comment by BrianZ111** [comment]
All good now, thanks!
